CREATE TABLE USER
(
    USER_NO NUMBER NOT NULL UNIQUE,
    USER_ID VARCHAR2(32) PRIMARY KEY,
    USER_PW VARCHAR2(32) NOT NULL,
    USER_NAME VARCHAR2(32),
    USER_PHONE VARCHAR2(32) NOT NULL UNIQUE,
    USER_EMAIL VARCHAR2(50)NOT NULL UNIQUE,
    USER_ADDRESS VARCHAR2(100),
    POSTDATE DATE,
    STATUS VARCHAR2(10)
);

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

